### ISSUE TITLE
Simulation code cannot allow for time varying interest rates

### ISSUE THREAD

**Issue by wdu9** [econ-ark/HARK#1106] opened 2022-01-22 00:25 UTC
**Describe the bug**
This is more of a design issue than it is a bug, however, the code does not allow Monte Carlo simulation of an agent if a list of interest rates is specified as opposed to a float. 

**To Reproduce**
Solve an agent who expects time varying interest rates and then try to use the simulate method. It should lead to an error.

**Comment by llorracc** [comment] 2022-01-22 17:48
@sbenthall, this would seem to interact with a couple of things you are working on: The rate of return on risky assets varies in the SHARKFIN context, and so you must be handling that somehow.  And you've been thinking about how to improve our handling of the timing of variables.  Will apparently came up with some workaround for the problem for his own purposes, but it's something that should be straightforward in baseline HARK.

**Comment by mnwhite** [comment] 2022-01-22 17:54
It is straightforward. You just make a subclass of IndShockConsumerType,
and then move `Rfree` from time_inv to time_vary in that class definition.
It's like 3-5 lines.

The existing solver will then work correctly if an instance of that
subclass has a time-varying list of Rfree values. Not all adjustments like
this will work correctly, however. If you try to change `CRRA` to be
time-varying like this, the solver will run, but the solution will be
somewhat incorrect.

**Comment by llorracc** [comment] 2022-01-22 18:03
I believe that @wdu9 had said that the solver already works (maybe after having already made the small changes you mentioned); the problem he identified was that even when the problem has been solved correctly, the simulation does not work.

**Comment by mnwhite** [comment] 2022-01-22 18:06
Oh right right, I misread. Yes, you have to overwrite the getStates()
method as well.

**Comment by sbenthall** [comment] 2022-01-22 21:20
In SHARKFin, the variable rate of return during simulation is being computed by the external ABM financial market, which runs in an alternating way with the HARK simulation.

It's quite awkward at this point and I would love it if the simulation code was written in a way that was more extensible, with documented API endpoints for external functions.

**Comment by llorracc** [comment] 2022-01-24 04:26
In my conv with @wdu9 , I proposed that the way the sims ought to work is that it should be possible to sim for a period, inspect the entrails of the system, modify them if desired, then sim for another period.  Is that what you are already doing, Seb, modifying the return each time given what comes from the ABM side of things?  If so then maybe you can explain to Will how you're doing it because that's something he needs to be able to do for the notebook he's writing...

**Comment by sbenthall** [comment] 2022-01-24 12:53
What you're describing is possible with the current HARK code, but certainly could be better supported.

What's happening currently in SHARKFin is a bit more complicated, because different kinds of operations happen at different frequencies: a daily update of asset values; an update of expectations of the risky asset at an exogenously determined 'attention' rate; and a quarterly 'macro-update' of labor and dividend income, as well as consumption.

@wdu9 I believe you have my email. Feel free to reach out and we can schedule a time to chat about this.

**Comment by llorracc** [comment] 2022-01-24 14:21
I think one of the things Will was confused about was the whole "newborns do not have a value of a_{t-1} because there is no _{t-1} in period t=0" issue.  In principle that is now solved by declaring that there is a new variable, $K$, satisfying the transition equation $k_{t} = a_{t-1}$.  Now newborns can begin life with a distribution of $k_{0}$ even if there is no $a_{t-1}$.

@wdu9, please reach out to Seb to figure out how to do what you thought could not be done in current HARK, and when you figure it out if you could make a PR that contains some modifications to the documentation or to comments in the code or something such that if those things had existed a few months ago when you first encountered this problem then `wdu9_{t-1}` would have realized how to do what you want to do.

**Comment by sbenthall** [comment] 2022-01-26 20:41
Talking with @wdu9 now...

One key challenge for this feature request is that the time-varying interest rate should be varying with the simulation clock `t_sim`, _not_ the age of each individual agent. In essence, the interest rate is actually a kind of aggregate shock value, though in the current models it is a shock with 0 variance. This is quite deeply connected with issue #1107

This means that looping through all `t in self.T_cycle` as is done with the shocks is not the right way to go here. Though in @wdu9 's immediate use cases, he has `T_sim == T_cycle`, and agents are "reborn" into the same "age" as the ones that died, which is why he added this hack:

https://github.com/econ-ark/HARK/blob/9562cafef854d9c3d6b4aba2540e3e442ba6ec6c/HARK/ConsumptionSaving/ConsIndShockModel.py#L1712-L1715

However, this is not a good permanent solution. Better support for this whole paradigm of modeling -- where there are aggregate factors that extend throughout the `T_sim` duration, is needed.

One way forward on this would build on #1101 and the related feature of `make_shock_history`. If the interest rate were a shock, then its values for the `T_sim` duration could be added as precomputed shock history, as opposed to as AgentType parameters.

(In general equilibrium models, the interest rate might be an aggregate state variable.)

**Comment by sbenthall** [comment] 2022-01-26 20:59
Related to #890 and #991

**Comment by llorracc** [comment] 2022-01-27 00:44
> Better support for this whole paradigm of modeling -- where there are aggregate factors that extend throughout the `T_sim` duration, is needed.

Yes.

What @wdu9 has done here is to cleverly hijack the machinery for the life cycle model that allows for predictable patterns over an idiosyncratic person's lifetime to allow him to capture predictable _aggregate_ shocks.  I'm still not quite getting why the simulation code does not work, but given that it is being used in a way considerably different from what it was designed for that's not too surprising.  Probably the quickest solution would be do the simulations differently if self.PerfMITShk is True (not just in the one way accomplished in lines 1712-1715 above, but in whatever other places that is necessary).  @wdu9, is it clear to you what would need to be done differently and how to do it?

**Comment by sbenthall** [comment] 2022-01-27 13:42
See this comment for a proposal for how to distinguish between different kinds of time-varying parameters in the model configuration:
https://github.com/econ-ark/HARK/issues/620#issuecomment-813452967

In a nutshell, the idea is to use different types for different kinds of model specifications. Something like:
 - CyclicProcess - a process that iterates repeatedly for each agent of the course of their life (T_cycle with cycles = 0 or cycles > 1)
 - AgeProcess - a process that spans the entire lifetime of an agent (T_cycle with cycles = 1)
 - TimeProcess - a process that spans the entire length of the simulation (T_sim)

**Comment by Mv77** [comment] 2022-01-28 19:33
@llorracc has asked me to go over this. Commenting so that I get notified and can find it later.

**Comment by Mv77** [comment] 2022-01-29 22:58
Just read this exchange, here are my thoughts.

**1. The issue that will is reporting, as he is reporting it, should be easy to fix.**

It should be a matter of adding `Rfree` to `time_vary` and changing the  necessary simulation methods (`get_Rfree()` would be the initial one I suppose).

This fix would allow us to solve and simulate life-cycle problems where the return factor is age-dependent.

**2. It seems like solving life-cycle problems where the return factor is age-dependent is not @wdu9 's actual goal.**

My best indirect inference of what Will wants to do is to have an agent who:
- Has a life cycle that I will index with `a`. Things like the probability of death are a function of `a`.
- Knows that at some simulation time `t=tau` there will be a one-time change in `Rfree`. After that, the return factor will revert to its original value.

The issue here is that both `t` and `a` are state variables. It is different from a solution point of view to be `a=5` years old at `t=tau-5` than at `t=tau-3`. To accommodate this kind of thing and allow time-varying AgeProcesses and TimeProcesses as @sbenthall suggests, we'd need to have `T_cycle * T_sim` solutions. (In the particular example I've given, all solutions for `t>tau` will be the same).

I do not think HARK currently supports stochastic processes that are a function of time, only of age. This might not be a bad thing. I think adding a time-dependent process inside the agent might be more trouble than it is worth.

**3. Would Will's method work better as a function that does not belong to AgentType?**

If I wanted to solve the problem proposed in **2.**, I'd write an external function that
1. Took an `AgentType` and some description of the time-varying process.
2. Created `tau` instances of the class, each with a life cycle indexed by `a`. In each of them `R` would be time-varying and for the agent corresponding to time `t`, `R` would change at `a = tau - t`.
3. I'd code a way to simulate that took the controls from the t-th agent at time t.

This would be hacky and specific. But, I would pose that the request that I have inferred in **2.** is also quite specific and something that we might not want to re-design the architecture of the toolbox around.

That said, **1.** should be resolved.

**Comment by llorracc** [comment] 2022-01-30 16:42
> 1. The issue that Will is reporting, as he is reporting it, should be easy to fix.

That was what Matt said, and what I thought too, but apparently when Will and Seb spoke, Will managed to convince Seb it was harder than that. 

> 2. It seems like solving life-cycle problems where the return factor is age-dependent is not @wdu9 's actual goal.

Has a life cycle that I will index with a. Things like the probability of death are a function of a.

"age-dependent" is the key term here.  

> **2. It seems like solving life-cycle problems where the return factor is age-dependent is not @wdu9 's actual goal.**
> 
> My best indirect inference of what Will wants to do is to have an agent who:
> 
> * Has a life cycle that I will index with `a`. Things like the probability of death are a function of `a`.

No, Will's agents are infinite horizon agents so there's nothing in their problem that should depend on their age.  That's why he can repurpose the agent's 'periods-from-the-end' position as a tool to allow perfect foresight aggregate shocks at varying distances from the end of life.  

> I think adding a time-dependent process inside the agent might be more trouble than it is worth.

I'm not sure what you mean by "a time-dependent process inside the agent" -- I agree that what you articulate in point 3 should solve the problem, but it involves putting the "time-dependent process inside the agent"; and I think basically every possible solution will have to do the same thing.

 @wdu9, does @Mv77's proposal make sense to you?  (I guess what puzzles me is that it seems like you'd have had to do this with your transition matrix approach too, but if you were able to do it in that case I'm not sure why you perceived it couldn't be done in the monte carlo approach).

@alanlujan91, could you read over all of this?  I'd like you to add this to the desiderata for your new agent type.  Specifically, I think we should do with `Rfree` what we have done with the Permanent and Transitory shocks:  The actual interest rate paid by an individual agent should be the product of an individual and an aggregate component, 

```
Rfree = RfreeInd * RfreeAgg
```

and similarly 

```
Risky = RiskyInd * RiskyAgg
```

The most common use case for this would be the one articulated above:  We could have `RfreeAgg` experience shocks at different `ages` to allow us to capture the fact that at a point of calendar time a given (common) shock to the riskfree rate would hit people of different ages.  (In principle, we could also use this mechanism to allow, for example, for an age-varying interest rate to capture the fact that younger people have lower credit ratings and so pay higher rates).

**Comment by Mv77** [comment] 2022-01-30 18:24
> No, Will's agents are infinite horizon agents so there's nothing in their problem that should depend on their age. That's why he can repurpose the agent's 'periods-from-the-end' position as a tool to allow perfect foresight aggregate shocks at varying distances from the end of life.

Well yes, but I was trying to think of a general solution to achieve this kind of thing. It is my opinion that it would be a bad idea to bake a specific method that works only for infinite horizon agents into the agent class. My view is that this should be an external function to which you pass an agent and which figures out what to do with that agent to achieve what the algorithm needs.

**Comment by wdu9** [comment] 2022-01-30 20:10
@llorracc It is essentially clear to me for what I need to do allow time varying interest rates during simulations. What I had in mind is exactly what Mateo mentioned which is to change the get_Rfree() method and use the self.t_sim attribute to track the period of the simulation. However, this would be a hack and I would use the PerfMITShk boolean variable to use the hack. What I discussed with @sbenthall was that there is a hack/ugly fix to this, but it would not be elegant and more importantly would not be conducive to the rest of the HARK infrastructure. 

To summarize the problem, within the simulation methods, some simulation methods (and I believe all actually) are age dependent (get_shocks method under IndShockConsumerType) while my simulations are time, or period, dependent. This is why I will take advantage of the self.t_sim attribute as a quick hack. 

Seb proposed a solution that seemed very promising:

> See this comment for a proposal for how to distinguish between different kinds of time-varying parameters in the model configuration: [#620 (comment)](https://github.com/econ-ark/HARK/issues/620#issuecomment-813452967)
> 
> In a nutshell, the idea is to use different types for different kinds of model specifications. Something like:
> 
>     * CyclicProcess - a process that iterates repeatedly for each agent of the course of their life (T_cycle with cycles = 0 or cycles > 1)
> 
>     * AgeProcess - a process that spans the entire lifetime of an agent (T_cycle with cycles = 1)
> 
>     * TimeProcess - a process that spans the entire length of the simulation (T_sim)

**Comment by Mv77** [comment] 2022-01-30 21:00
Seb's solution makes time a state variable. We'd have to have solutions for every `(time, age)` pair. Thus, we'd have to re-work the solution and simulation methods to incorporate this new dimension.
(I get that in your case age is irrelevant because its an infinite horizon model, but we're talking Seb's general solution now)

This would be good in the sense that it would expand the class of models we can deal with. A an example of a model that could be accommodated with this change would be an OLG model with secularly declining interest rates: age matters and each generation is exposed to different interest rates.

It would definitively have benefits, but my concerns would be:
- It's a substantial rework. Might not be worth it to implement it as a general feature if there is only a limited need for it. That's why it might be worth it to have it as a hacky external function.
- Its a general consensus that HARK's terminology around time is confusing. Imagine layering another dimension over it. Might it raise the entry barriers?

**Comment by sbenthall** [comment] 2022-01-31 02:03
If the agents are infinite horizon agents with a single period in their "cycle", then time-varying interest rates in simulation are the values of an exogenous shock over time. The solver consider a specific distribution for that shock.

That is how this connects to #1107 -- which is about making the interest rate an exogenous shock. Then the different values at different times used in simulation can be entered with the preloaded shock histories.

In other words, I think that fixing #1107 is the best way to solve this issue.

I'm afraid bringing up different types of time-varying agent configurations was a bit of a red herring here. @Mv77 you make a good points that this explodes the solution space, and raises other issues. I think they should be discussed in a different issue.

I would much prefer we did not commit what we know to be mere hacks into the core library. I understand that this library is used for many student projects, but it is also public facing and something that we know is poor design for a single specific use makes the library more difficult to understand for any other potential users. It is easy to make a fork of the repository with custom hacks if that's needed for a specific project.

**Comment by Mv77** [comment] 2022-01-31 04:26
> If the agents are infinite horizon agents with a single period in their "cycle", then time-varying interest rates in simulation are the values of an exogenous shock over time. The solver considers a specific distribution for that shock.

The difficulty is that the distribution is time-varying and degenerate at every `t`.

> In other words, I think that fixing #1107 is the best way to solve this issue.

I don't think it will. That issue wants `R` to be a random variable with a stable distribution. This issue wants it to be a time-varying constant. This one is much harder as time becomes a state.

**Comment by llorracc** [comment] 2022-01-31 04:36
I agree with @Mv77.  What @wdu9 described as a "hack" only appears that way because it is not something that was originally contemplated in the original design of the system.  The sequence space method(s) had not been invented then.  But matters are now clear:

1. There is a compelling case for allowing for time dependent shocks that appear an arbitrary number of periods in the future.
2. There's no other way to do that (not just within our framework; mathematically, conceptually, there's no alternative to computing all of the objects in what Will called a "hack"
3. It will not seem like a hack (it will not BE a hack) if we build some infrastructure to do it as conveniently as it can be done.

**Comment by sbenthall** [comment] 2022-01-31 15:22
> degenerate

I don't think this has been said yet, but as a matter of design, I think it would be best if HARK understood that scalar values are degenerate distributions, and that HARK agents were parameterized by distributions explicitly.

So, for example, in #1012 the income shocks are now configured as IndexDistributions that take an engine, which is of type Distribution, and time-varying parameters. We can use the same construction with a new degenerate distribution class, (maybe named Scalar), which can likewise be passed to the IndexDistribution.

That's at least how it could work conceptually. I believe there may be ways to tell Python to just understand that, say, a float can be of type Distribution, if we want something lighter weight on the backend. But the point is that with a clean design, which I think we are all interested in getting HARK towards, if models are parameterized with distributions (#620) then it should be trivial to deal with the degenerate case.

**Comment by llorracc** [comment] 2022-01-31 15:37
I'm sympathetic to this point, but when we rethink the design we need to think carefully about whether we should go even further.  If we describe each potentially stochastic object with its own standalone distribution, that would hard-wire an assumption that all our stochastic variables are distributed independently from each other.  There are important cases where the stochastic variables need to be correlated.  In that case, they really need all to be drawn simultaneously at the beginning of the period, so that their joint distribution can be baked in from the outset -- as Pablo does in Dolo.

**Comment by sbenthall** [comment] 2022-01-31 15:44
Good point @llorracc that's a use case to be supported for sure.

**Comment by sbenthall** [comment] 2022-01-31 16:11
> 3\. It will not feel like a hack (it will not BE a hack) if we build some infrastructure to do it as conveniently as it can be done.

> It's an _aspect_ of the solver. Not an "issue" in the sense of something that needs to be fixed

> This needs to be hard wired into their solution

I feel like my tone may be misunderstood. I understand that there are new computational steps needed for this method, and that @wdu9 has found a way to compute most of these steps with the current code base.

My use of the term "hack", "issue", etc. is solely with respect the the ergononomics and code quality issues which we seem to all be in agreement about.

Based on what you've just explained, it sounds like the sequence space method is a use case that is currently unanticipated by the main `solve_agent` code loop, which knows how to handle infinite horizon cases, or finite horizon cases, but not this hybrid case of a finitely known period followed by an infinite horizon:

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L878

I wonder how this case can be better supported by the core library code.

**Comment by llorracc** [comment] 2022-01-31 16:23
Yes, I think we are now in agreement that the question is how to change things so that it becomes much easier to see how to do this kind of thing.  Accomplishing it does not require fundamental structural changes to the code, it just requires tools to help users construct these kinds of experiments transparently.  

@sbenthall, this is perhaps something that could fit into your agenda of improving our infrastructure for handling ex-ante heterogeneity.  Not only do we want to handle heterogeneity in, say, relative risk aversion or time preference rates.  We need, for these purposes, to handle agents who are heterogeneous in the "age" at which a particular event that we think of as fixed in time hits them.  If the event is at date $t$, then agents who were born in period $t-1$ would have the event hit them at age 1, while agents who were born in period $t-50$ would have it hit them in period 50 of their lives.  Simulation of the entire economy would entail simulation of the suite of agents where there were the right number of agents for whom the shock hits at each age.

**Closed** 2023-02-06 17:28 UTC
