### ISSUE TITLE
Fail to run testing examples

### ISSUE THREAD

**Issue by luzk-emory** [econ-ark/HARK#234] opened 2019-03-07 01:08 UTC
The pkg I downloaded one week ago worked. When using the latest version downloaded today, I ran into a problem. The error messages are pasted below:
```
$ python
Python 2.7.15 |Anaconda, Inc.| (default, Feb 21 2019, 11:55:13) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> execfile("Testing/Comparison_UnitTests.py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Testing/Comparison_UnitTests.py", line 23, in <module>
    from HARK.ConsumptionSaving.ConsIndShockModel import solvePerfForesight, IndShockConsumerType
  File "HARK\ConsumptionSaving\ConsIndShockModel.py", line 26, in <module>
    from HARK.interpolation import CubicInterp, LowerEnvelope, LinearInterp
  File "HARK\interpolation.py", line 1645
    def __init__(self, *functions, nan_bool = True):
                                          ^
SyntaxError: invalid syntax
>>> execfile("Testing/ModelTesting.py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Testing/ModelTesting.py", line 300, in <module>
    import HARK.ConsumptionSaving.TractableBufferStockModel as Model
  File "HARK\ConsumptionSaving\TractableBufferStockModel.py", line 32, in <module>
    from HARK.interpolation import CubicInterp
  File "HARK\interpolation.py", line 1645
    def __init__(self, *functions, nan_bool = True):
                                          ^
SyntaxError: invalid syntax
>>> execfile("Testing/MultithreadDemo.py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Testing/MultithreadDemo.py", line 20, in <module>
    import HARK.ConsumptionSaving.ConsIndShockModel as Model # Consumption-saving model with idiosyncratic shocks
  File "HARK\ConsumptionSaving\ConsIndShockModel.py", line 26, in <module>
    from HARK.interpolation import CubicInterp, LowerEnvelope, LinearInterp
  File "HARK\interpolation.py", line 1645
    def __init__(self, *functions, nan_bool = True):
                                          ^
SyntaxError: invalid syntax
```
I suspect there is a bug in the original code. Could someone help me?

**Comment by llorracc** [comment] 2019-03-07 01:47
Thanks for this input!  One possibility is that it has to do with python2 vs python3.  We've been converting over from python2 to python3 and trying to keep the new code compatible, but have found it to be more subtle than we thought.  Have you tried running on python3?

**Comment by mnwhite** [comment] 2019-03-07 02:01
It actually seems to be a bug that came up when I merged Tim Munday's
nan_bool PR.  It works properly in Py3, but Travis testing indicates that
it fails on Py2.  I see now what the problem is: nan_bool is an optional
input after a list of inputs (*functions) in the __init__ method of
LowerEnvelope (etc).  This is apparently allowed in Py3 but not Py2.  At
least I now know what to fix!

Thank you for bringing this to our attention-- your error output pointed me
to what was going wrong.

**Comment by mnwhite** [comment] 2019-03-07 02:02
To be clear: I will fix this tomorrow morning.  It breaks HARK in Py2 and needs to be fixed immediately.

**Comment by mnwhite** [comment] 2019-03-07 14:12
This has been fixed in the master branch by undoing the PR that broke Py2.  I attempted a simple fix, but it didn't work.  More extensive work is required.

**Closed by mnwhite** 2019-03-07 14:12 UTC
