### ISSUE TITLE
Move illustration of Bayer & Luetticke invocation of DCT & fixed copula to DemARK repository

### ISSUE THREAD

**Issue by shaunagm** [econ-ark/HARK#361] opened 2019-07-22 14:07 UTC
See [discussion in PR #344](https://github.com/econ-ark/HARK/pull/344#issuecomment-512956222) for context.

**Comment by llorracc** [comment] 2020-03-18 11:34
Actually, it should move to REMARK, because it needs a file structure (and because it is about reproducing the results of someone else's paper)

**Comment by sbenthall** [comment] 2020-03-18 12:43
closing as duplicate of #531

**Closed by sbenthall** 2020-03-18 12:43 UTC
