### ISSUE TITLE
error in executing the first line of Demo.py

### ISSUE THREAD

**Issue by asmileguo** [econ-ark/HARK#80] opened 2016-09-13 17:00 UTC
Hi,
I am a new comer here. Forgive me if my question sounds stupid. 
I run into problem when running the first line of Demo.py (under the folder "ConsumptionSaving")

**from ConsIndShockModel import IndShockConsumerType**

All that I did was just to enter that folder and execute this first line. The error message is:

**File "C:\Users...\Documents\Python\HARK\ConsumptionSaving\ConsIndShockModel.py", line 2242**
    **raise Exception, "grid_type not recognized in **init**." + \**
                   **^**
**SyntaxError: invalid syntax**

I use Anaconda. Any insight? Thanks.

**Comment by dclow** [comment] 2016-09-13 17:19
That's really odd.  It seems like it's trying to execute line 2242 of "ConsIndShockModel.py" without also executing line 2243, which is what the + \ at the end is telling it to do

Are you using Spyder?  How are you executing Python code?  Have you changed any of the files at all?

**Comment by asmileguo** [comment] 2016-09-13 19:19
I found that changing line 2242 into 
**raise Exception("grid_type not recognized in __init__." + \
                             "Please ensure grid_type is 'linear' or 'exp_mult'")**
solves the problem (at least for the first line error I mentioned).
Was it due to different versions of Python? I run it in Python 3 Jupyter notebook.

**Comment by dclow** [comment] 2016-09-13 19:26
Hmmmmm yeah that sounds very possible.  HARK is written for and tested in Python 2.7

I'd recommend downloading and installing Python 2.7 if you want to use HARK.  If that doesn't fix the problem, please let me know

**Comment by asmileguo** [comment] 2016-09-13 22:42
Thanks David. I'll just check how far it can go with Python 3.

**Comment by compumetrika** [comment] 2016-09-14 12:27
I can confirm that the error described above occurs under python 3, but not python 2. 

Here is my effort to run the demo with Python 3: 

    $ cd ~/workspace/HARK/ConsumptionSaving/
    $ python3 Demo.py 
    Traceback (most recent call last):
      File "Demo.py", line 27, in <module>
        from ConsIndShockModel import IndShockConsumerType
      File "/home/npalmer/workspace/NEW_HARK/ConsumptionSaving/ConsIndShockModel.py", line 2242
        raise Exception, "grid_type not recognized in __init__." + \
                       ^
    SyntaxError: invalid syntax


...the same error. 

Under Python2.7: 

    $ python Demo.py 
    divide by zero encountered in log
    Consumption functions:
    MPC out of Credit v MPC out of Income
    $


As @dclow noted, HARK has been written for Python 2.7; unfortunately this appears to be one of the places that Python 2/3 differences crop up. Ideally our code would run under both, but as noted above it has only been tested in Python 2.7. There may be more to be said on this. 

Thanks for catching this. (Not closing the issue just yet.)

**Comment by asmileguo** [comment] 2016-09-15 04:08
@compumetrika @dclow Thanks for the help. I also confirmed that I could run it on Python 2.7 on my machine without any issues.

**Comment by mnwhite** [comment] 2016-09-29 14:42
Should we close this issue now, and replace it with one entitled "make HARK compatible with Python 3"?

**Comment by mnwhite** [comment] 2017-01-09 21:02
Closing because no one has objected to my suggestion for three months.

**Closed by mnwhite** 2017-01-09 21:02 UTC
