### ISSUE TITLE
Choose a reproducibility platform/workflow

### ISSUE THREAD

**Issue by brainwane** [econ-ark/HARK#188] opened 2018-08-04 15:47 UTC
Right now, to store and share replications and reproductions, [we use a special-purpose repository called "REMARK: Replications and Explorations Made using the ARK"](https://github.com/econ-ark/REMARK/). We're investigating whether we should stay with that or choose a different approach.

@llorracc has [asked our NumFOCUS peers](https://groups.google.com/forum/#!topic/numfocus/ZMQNgeSqvY0) what they're using and recommending, and I've [asked peers within The Carpentries](https://carpentries.topicbox.com/groups/discuss/T45d1f9e935d7181b) the same question.

Let's share notes here in this GitHub thread and make the decision here.

**Comment by llorracc** [comment] 2018-08-04 16:11
Good idea to use a GitHub thread for this -- since GitHub itself is likely to be an integral part of whatever the answer will prove to be.  

One other point is that we will need not only to choose a technology, but also:

1. Create some working examples of the use of that technology
1. Create materials for teaching students to use the technology
   * This may mostly involve a curated set of links to existing materials

**Comment by llorracc** [comment] 2018-08-04 16:31
So far (2018-08-04) the numfocus discussion has surfaced two candidates that we had not found before:

## [Sumatra](https://pythonhosted.org/Sumatra/introduction.html) 
The mission statement is spot-on for what we are trying to achieve. But we are not sure how active the project is, or whether it aims to expand to fields other than its home in neuroscience.

## [Datalad](https://www.datalad.org/for/reproducible-science)

Datalad’s aim is to record virtually every step in a whole neuroscience research project (code, data, writing, etc). For a team of people with a complete grasp of Datalad and a lot of experience with it, this sounds like it might be a great tool.  It could be adapted to our narrower purposes, but how easily is unclear.

We've also looked at less specialized tools including:

1. [RunMyCode.org](http://runmycode.org)
1. [Dataverse.org](http://dataverse.org)
1. [VisTrails](https://www.vistrails.org/index.php/Main_Page)
1. [Stencila](https://stenci.la/)
1. [ReproZip](https://www.reprozip.org/)

but in our quick assessment none of them looked to have the combination we are seeking of being:  

1. Lightweight (don't ask too much of the authors)
1. Future-proof (if the project dies, is the archive still usable)
1. Focused on our goal
    * Not just archiving code, but ensuring that it runs and will continue to be runnable indefinitely

**Comment by VickySteeves** [comment] 2018-08-05 14:07
I believe ReproZip is on-mission for you! It takes 2 steps for folks to bundle their worm with ReproZip, and ReproZip not only captures all data and code, but the *environment* in which everything runs is captured. ReproZip gets everything needed to rerun someone's work and creates a single distributable bundle of it. You can see examples at: https://examples.reprozip.org

I actually wrote a paper about how since the ReproZip format is generalizable, it's great for archival purposes (I'm a librarian trained in digital preservation): https://iassistquarterly.com/index.php/iassist/article/view/18

ReproZip has unpackers (docker, vagrant), but doesn't *rely* on them to rerun the bundle. We are actually adding singularity as an available unpacker now! 

Anyway, sorry to butt into your issue/convo, just wanted to add some additional info!

**Comment by mnwhite** [comment] 2018-09-04 13:03
That sounds promising.

**Comment by shaunagm** [comment] 2019-04-25 16:43
Closing this, it's closely related to [Overark's issue #5](https://github.com/econ-ark/OverARK/issues/5) so we can discuss it there.

**Closed by shaunagm** 2019-04-25 16:43 UTC
