### ISSUE TITLE
AgentType subclass preSolve() inconsistently calls superclass preSolve()

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#576] opened 2020-03-17 16:39 UTC
AgentType defines a `preSolve()` method with two functions:
 - (1) running checkRestrictions (see #574) 
 - (2) essentially type checking the time-varying parameters

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L417

This method is sometimes called by the overwriting `preSolve` of subclasses, and sometimes isn't.
However, functionality (2) is, if I'm not mistaken, consistently valuable for all subclasses.

In this case, the superclass method is called:
https://github.com/econ-ark/HARK/blob/d1a8eb90ebe34a93801ead8655b5e29ef9d1e3eb/HARK/ConsumptionSaving/ConsMarkovModel.py#L733

In this case, the method is overwritten and `checkConditions` is put in its place:
https://github.com/econ-ark/HARK/blob/3d3dbfea9f2192213ece38ca6912ed249336e392/HARK/ConsumptionSaving/ConsIndShockModel.py#L2260

In this case, the superclass call is simply omitted.
https://github.com/econ-ark/HARK/blob/d1a8eb90ebe34a93801ead8655b5e29ef9d1e3eb/HARK/ConsumptionSaving/ConsRepAgentModel.py#L215

I think something has gone wrong here, but I'm not sure what.

**Comment by sbenthall** [comment] 2020-03-17 16:43
This a case where the software author appears ambivalent about whether or not to call the superclass method.
https://github.com/econ-ark/HARK/blob/d1a8eb90ebe34a93801ead8655b5e29ef9d1e3eb/HARK/ConsumptionSaving/ConsAggShockModel.py#L117

**Comment by mnwhite** [comment] 2020-03-17 16:46
The original preSolve() method in AgentType was just a dummy method that
had nothing but pass.  It was there because preSolve() is called
automatically by solve(), but any particular subclass might not actually
have anything useful to do in a pre-solution step.  Later,
checkRestrictions was added (by Dave Low?) to verify that time-varying
parameters were actually lists, and maybe also check that Markov parameters
were formatted appropriately.

Roughly: Originally there was no point in calling super.preSolve() for
classes that were defined directly from AgentType, because it did nothing,
but later that changed and we didn't notice.

**Comment by mnwhite** [comment] 2024-07-03 14:25
Closing because pre_solve works as intended for all classes. It would be better with the "de-inheritance" overhaul, however.

**Closed by mnwhite** 2024-07-03 14:25 UTC
Labels: Design
