### ISSUE TITLE
Output from solve() unclear

### ISSUE THREAD

**Issue by nicksawhney** [econ-ark/HARK#1037] opened 2021-07-08 18:17 UTC
A basic agent yields the following output when solved
```
>>agent = IndShockConsumerType()
>>agent.cycles = 0
>>agent.solve()

GPFRaw                 = 0.984539 
GPFNrm                 = 0.993777 
GPFAggLivPrb           = 0.964848 
Thorn = APF            = 0.994384 
PermGroFacAdj          = 1.000611 
uInvEpShkuInv          = 0.990704 
VAF                    = 0.932054 
WRPF                   = 0.213705 
DiscFacGPFNrmMax       = 0.972061 
DiscFacGPFAggLivPrbMax = 1.010600 
```

For a new user, this output is quite unclear. It could be better documented or the output could be more expressive.

**Comment by mnwhite** [comment] 2021-07-08 18:36
This output should not be printed to screen when this agent is solved; I
don't think this is intended behavior. These are some summary statistics
about the solution to this agent's problem, but they should not be printed
to screen by default when the agent is solved. I think a line of test code
was mistakenly left uncommented/undeleted.

**Comment by mnwhite** [comment] 2024-07-10 14:29
The problem was a default setting for check_conditions, which has been resolved. Closing.

**Closed by mnwhite** 2024-07-10 14:29 UTC
