### ISSUE TITLE
No default MrkvArray for 𝙼𝚊𝚛𝚔𝚘𝚟𝙲𝚘𝚗𝚜𝚞𝚖𝚎𝚛𝚃𝚢𝚙𝚎

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#590] opened 2020-03-20 15:05 UTC
No default MrkvArray parameter for 𝙼𝚊𝚛𝚔𝚘𝚟𝙲𝚘𝚗𝚜𝚞𝚖𝚎𝚛𝚃𝚢𝚙𝚎,

which cause an error on initialization with 𝙼𝚊𝚛𝚔𝚘𝚟𝙲𝚘𝚗𝚜𝚞𝚖𝚎𝚛𝚃𝚢𝚙𝚎()
```
~/projects/econ-ark/HARK/HARK/ConsumptionSaving/ConsMarkovModel.py in updateSolutionTerminal(self)
    763 
    764         # Make replicated terminal period solution: consume all resources, no human wealth, minimum m is 0
--> 765         StateCount = self.MrkvArray[0].shape[0]
    766         self.solution_terminal.cFunc   = StateCount*[self.cFunc_terminal_]
    767         self.solution_terminal.vFunc   = StateCount*[self.solution_terminal.vFunc]

AttributeError: 'MarkovConsumerType' object has no attribute 'MrkvArray'
```

**Comment by mnwhite** [comment] 2020-03-20 15:14
The problem is that there's no decent concept of a "default" Markov model.
We can make an arbitrary choice, I supposed.

All of the other models have properly working default dictionaries in PR
#585.

**Comment by sbenthall** [comment] 2020-03-20 15:20
My sense is that there are two divergent ideas in play about model parameters defaults.

- There's the idea that the default parameters in the HARK models should be illustrative or realistic in some way; the default use of these classes should be substantive for economists.

- There's a different idea, more from a software perspective, that the default values of a function should be the simplest possible values that allow for execution of the program. These are often degenerate cases--0, None, etc. But they serve to show the expected type for the parameter and make things run smoothly if for whatever reason nobody bothers to set them

**Comment by llorracc** [comment] 2020-03-22 14:25
One way to think about it is this:  There are a good many contexts (like, a life cycle model calibration) where we certainly want to have a default calibration that is a reasonable starting point for substantive research.  There are some other contexts, like the Markov one, where the range of potential uses of the tool is profoundly heterogeneous, so there is no "natural" default.  

I'd propose that we address these issues in two ways:
1. Each model should have a distinct separate default calibration for testing computational functioning, which can be designed to do quick exercises specifically designed to test the functioning of the code with no concern about realism.
1. Models where an economically substantive "plausible" calibration of the model is available (like the life cycle model) should have such a calibration as their default
1. Models that are general-purpose (like the Markov case) should pick some specific and transparent (and simple) particular realistic model.
    * Like, for the Markov case, maybe a stochastic transition process between employment and unemployment

**Comment by mnwhite** [comment] 2024-07-03 14:28
This was fixed with the constructors overhaul, closing.

**Closed by mnwhite** 2024-07-03 14:28 UTC
